name: release-please
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          include-component-in-tag: true
          token: ${{ secrets.RELEASE_PLEASE_PAT }}
      - name: Show config actually on main
        run: |
          echo "== release-please-config.json on main =="
          git show origin/main:release-please-config.json || true
          echo "== manifest on main =="
          git show origin/main:.release-please-manifest.json || true
